const data = {
    users: [
        {
            name: "Sakib Hasan",
            email: "sakib100.sa@gmail.com",
            password: "Sakib@14168",
            phone: "01700000000",
            address: "Dhaka, Bangladesh",
            // image: "public/images/users/default-user.png",
            isAdmin: true,
        },
        {
            name: "Tanvir Ahmed",
            email: "tanvir@gmail.com",
            password: "Sakib@14168",
            phone: "01700000000",
            address: "Dhaka, Bangladesh",
            image: "public/images/users/default-user.png",
            isAdmin: false,
        },
        {
            name: "Shakil Ahmed",
            email: "sakilahmed@gmail.com",
            password: "Sakib@14168",
            phone: "01700000000",
            address: "Dhaka, Bangladesh",
            image: "public/images/users/default-user.png",
            isAdmin: false,
        },
        {
            name: "Shamim Haque",
            email: "shamim@gmail.com",
            password: "Sakib@14168",
            phone: "01700000000",
            address: "Dhaka, Bangladesh",
            image: "public/images/users/default-user.png",
            isAdmin: false,
        },
    ],
    products: [
        {
            name: "iPhone 14 Pro Max",
            slug: "iphone-14-pro-max",
            description:
                "The iPhone 14 Pro Max is the most advanced iPhone ever. It features the largest display ever on an iPhone, a new A16 Bionic chip, and Pro camera system with 10-bit Dolby Vision HDR recording.",
            price: 1999.99,
            quantity: 100,
            sold: 0,
            shipping: 100,
            image: "public/images/products/iphone-14-pro-max.jpg",
            category: "65d10ec543203894535e4729",
        },
        {
            name: "Samsung Galaxy S22 Ultra",
            slug: "samsung-galaxy-s22-ultra",
            description:
                "The Samsung Galaxy S22 Ultra is the most advanced Galaxy ever. It features the largest display ever on a Galaxy, a new Exynos 2200 chip, and Pro camera system with 10-bit Dolby Vision HDR recording.",
            price: 1499.99,
            quantity: 100,
            sold: 0,
            shipping: 100,
            image: "public/images/products/samsung-galaxy-s22-ultra.jpg",
            category: "65d10ec543203894535e4729",
        },
        {
            name: "Google Pixel 7 Pro",
            slug: "google-pixel-7-pro",
            description:
                "The Google Pixel 7 Pro is the most advanced Pixel ever. It features the largest display ever on a Pixel, a new Tensor chip, and Pro camera system with 10-bit Dolby Vision HDR recording.",
            price: 999.99,
            quantity: 100,
            sold: 0,
            shipping: 100,
            image: "public/images/products/google-pixel-7-pro.jpg",
            category: "65d10ec543203894535e4729",
        },
        {
            name: "Apple MacBook Pro 16",
            slug: "apple-macbook-pro-16",
            description:
                "The Apple MacBook Pro 16 is the most advanced MacBook ever. It features the largest display ever on a MacBook, a new M2 chip, and Pro camera system with 10-bit Dolby Vision HDR recording.",
            price: 2999.99,
            quantity: 100,
            sold: 0,
            shipping: 100,
            image: "public/images/products/apple-macbook-pro-16.jpg",
            category: "65d111539fdc546695c30b7a",
        },
        {
            name: "Dell XPS 15",
            slug: "dell-xps-15",
            description:
                "The Dell XPS 15 is the most advanced Dell ever. It features the largest display ever on a Dell, a new Intel Core i9 chip, and Pro camera system with 10-bit Dolby Vision HDR recording.",
            price: 1999.99,
            quantity: 100,
            sold: 0,
            shipping: 100,
            image: "public/images/products/dell-xps-15.jpg",
            category: "65d111539fdc546695c30b7a",
        },
        {
            name: "HP Spectre x360",
            slug: "hp-spectre-x360",
            description:
                "The HP Spectre x360 is the most advanced HP ever. It features the largest display ever on a HP, a new Intel Core i9 chip, and Pro camera system with 10-bit Dolby Vision HDR recording.",
            price: 1499.99,
            quantity: 100,
            sold: 0,
            shipping: 100,
            image: "public/images/products/hp-spectre-x360.jpg",
            category: "65d111539fdc546695c30b7a",
        },
        {
            name: "Sony A7 IV",
            slug: "sony-a7-iv",
            description:
                "The Sony A7 IV is the most advanced Sony ever. It features the largest display ever on a Sony, a new Exmor R CMOS sensor, and Pro camera system with 10-bit Dolby Vision HDR recording.",
            price: 1999.99,
            quantity: 100,
            sold: 0,
            shipping: 100,
            image: "public/images/products/sony-a7-iv.jpg",
            category: "65d112d3e7e4d8f364698482",
        },
        {
            name: "Canon EOS R5",
            slug: "canon-eos-r5",
            description:
                "The Canon EOS R5 is the most advanced Canon ever. It features the largest display ever on a Canon, a new CMOS sensor, and Pro camera system with 10-bit Dolby Vision HDR recording.",
            price: 2999.99,
            quantity: 100,
            sold: 0,
            shipping: 100,
            image: "public/images/products/canon-eos-r5.jpg",
            category: "65d112d3e7e4d8f364698482",
        },
        {
            name: "Nikon Z9",
            slug: "nikon-z9",
            description:
                "The Nikon Z9 is the most advanced Nikon ever. It features the largest display ever on a Nikon, a new CMOS sensor, and Pro camera system with 10-bit Dolby Vision HDR recording.",
            price: 3999.99,
            quantity: 100,
            sold: 0,
            shipping: 100,
            image: "public/images/products/nikon-z9.jpg",
            category: "65d112d3e7e4d8f364698482",
        },
    ],
};

module.exports = data;
